openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Local
  - url: http://localhost:9000
    description: Specmatic Stub Server
paths:
  /products/{id}:
    get:
      summary: Get Products
      description: Get Products
      parameters:
        - in: path
          name: id
          schema:
            type: integer  # Corrected type from 'number' to 'integer'
          required: true
          description: Numerical Product Id
      responses:
        '200':
          description: Returns Product With Id
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  sku:
                    type: string

  /products:
    post:
      summary: Add Product
      description: Add Product
      requestBody:
        required: true  # Added required field
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - sku
              properties:
                name: 
                  type: string
                sku:
                  type: string
      responses:
        '200':
          description: Returns product id as an object
          content:
            application/json:
              schema: 
                type: object
                required:
                  - id
                properties:
                  id:
                    type: integer
